### ISSUE TITLE
Left stick issue

### ISSUE THREAD

**Issue by kLabz** [deepnight/ld47#1]
Hi! Congratz on your compo, I haven't finished it yet but will do later today for sure :D 

I saw you made some fixes regarding controls, but I can't make my xbox controller work correctly with current version: the left stick doesn't do anything (A etc. work just fine). I find it especially strange considering it works for my heaps game using your libs

Edit: may be worth mentioning I'm using firefox (so web version), I'll test with chromium
Edit 2: indeed, works fine in chromium, and left stick doesn't work on firefox with my game either.. my bad

**Comment by deepnight** [comment]
It *might* related to the way JS locks controllers if you happen to start the game in a tab and switch to another tab 🤔  Can you try that:

 - close any tab in FF that may be using pad controllers
 - close FF
 - open FF, run the game: https://deepnight.net/games/fort-loop/
 - check controls :)
