### ISSUE TITLE
Info - managing Life between levels

### ISSUE THREAD

**Issue by di-effe** [deepnight/ld47#3]
Hi, I'm studying and reworking this game as a learning exercise.

You left in the code the health system and I wanted to enabled again like in a standard platform, but I've a little problem understanding how you would pass the Life value to the next level, because the initlife function seems to run every time a level start.

A little hint would be appreciated, but sooner or later I'll figure it out 😊

**Comment by deepnight** [comment]
In this game, everytime the level changes or restarts, every Entity are destroyed and garbage collected. Therefore, if you want to keep some data, like`life` for the Hero, you will need to store these somewhere else.

My recommendation would be to have these in Game, and use getters/setters in Hero to still access the values in a fully transparent way.

**Comment by di-effe** [comment]
Thanks, I'll work on it
